# Generated by Django 4.2.3 on 2023-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchpapermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='filemodel',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodel',
            name='facultyPublication',
            field=models.ManyToManyField(null=True, to='researchpapermanagement.faculty'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='studentPublication',
            field=models.ManyToManyField(null=True, to='researchpapermanagement.student'),
        ),
    ]
