# Generated by Django 4.2.3 on 2023-07-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchpapermanagement', '0002_faculty_student_filemodel_description_filemodel_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
